# Generated by Django 4.2.5 on 2023-09-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='write',
            new_name='writer',
        ),
    ]
